/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *
 * Jan Veverka, Caltech, 25 Nov 2011
 * The Beta Generalised Hyperbolic Secant Distribution.
 * 
 * http://www.statistik.wiso.uni-erlangen.de/forschung/d0064.pdf
 * The Beta-Hyperbolic Secant (BHS) Distribution
 * Matthias J. Fischer, David Vaughan
 *****************************************************************************/

#ifndef JPSI_MUMU_ROOBETAGSHPDF_H
#define JPSI_MUMU_ROOBETAGSHPDF_H

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBetaGshPdf : public RooAbsPdf {
public:
  RooBetaGshPdf() {} ; 
  RooBetaGshPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width,
	      RooAbsReal& _t,
	      RooAbsReal& _beta,
	      RooAbsReal& _theta);
  RooBetaGshPdf(const RooBetaGshPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const {
    return new RooBetaGshPdf(*this,newname);
  }
  inline virtual ~RooBetaGshPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  RooRealProxy t ;
  RooRealProxy beta ;
  RooRealProxy theta ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooBetaGshPdf,1) // The Beta Generalised Secant Hyperbolic PDF
};
 
#endif
