/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROODRELLYAN
#define ROODRELLYAN

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooDrellYan : public RooAbsPdf {
public:
  RooDrellYan() {} ; 
  RooDrellYan(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width,
	      RooAbsReal& _R,
	      RooAbsReal& _I,
	      RooAbsReal& _alpha);
  RooDrellYan(const RooDrellYan& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDrellYan(*this,newname); }
  inline virtual ~RooDrellYan() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  RooRealProxy R ;
  RooRealProxy I ;
  RooRealProxy alpha ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooDrellYan,1) // Your description goes here...
};
 
#endif
